use_frameworks!

platform :ios, '10.0'

target 'NKUtility_Example' do
  pod 'NKUtility', :path => '../'

  target 'NKUtility_Tests' do
    inherit! :search_paths

    pod 'Quick'
    pod 'Nimble'
    pod 'FBSnapshotTestCase'
    pod 'Nimble-Snapshots' 
  end
end
